### ISSUE TITLE
Declared module version unnecessarily high

### ISSUE THREAD

**Issue by raidancampbell** [dmachard/go-clientsyslog#4]
Howdy!  Thanks for your work on this!

I was looking at using your library, but [specifying version](https://github.com/dmachard/go-clientsyslog/blob/main/go.mod#L3) `1.23` in the `go.mod` is still a bit too new for my infrastructure.

As far as I can tell, the library doesn't use any new features introduced in `1.23`, and can safely be declared to a lower version.  The `version` specified in the file is ["The minimum version of Go required by the current module."](https://go.dev/doc/modules/gomod-ref), so you can safely use go `1.23` to build a module that declares itself as something lower like `1.19`.

Am I reading the source wrong, or would it be possible to lower the module's go version?

**Comment by dmachard** [comment]
You're right, can you make a pull request to reduce the minimum version ?
